name: testenv
dependencies:
  - python=3.4
  - django >=1.6,<1.9
  - jinja2
  - docutils
  - future
  # optional requirements, depending on which serialization formats you want
  - pyyaml
  ## optional, for WebDAV support
  ##dexml
  ##fs
  ## optional, for PostgreSQL support
  ##psycopg2
  #

  - pip:
    - django-tagging >=0.4
    - httplib2
    - parameters
    # optional requirements, depending on which version control systems you use
    - hgapi
    - gitpython >=0.3.6
